-- ============================================================
-- Script completo Catálogo Mary Leggings
-- Ejecutar en el SQL Editor de Supabase (idempotente)
-- ============================================================

-- ============================================================
-- 1. CATEGORÍAS
-- ============================================================
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz default now()
);

-- ============================================================
-- 2. PRODUCTOS
-- ============================================================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  color text not null default '',
  descripcion text not null default '',
  categoria_id bigint references public.categories(id) on delete set null,
  imagen_url text not null default '',
  disponible boolean not null default true,
  fecha_activacion timestamptz default now(),
  created_at timestamptz default now()
);

-- Índices productos
create index if not exists idx_products_codigo on public.products(codigo);
create index if not exists idx_products_nombre on public.products(nombre);
create index if not exists idx_products_categoria on public.products(categoria_id);
create index if not exists idx_products_color on public.products(color);
create index if not exists idx_products_disponible on public.products(disponible);

-- ============================================================
-- 3. IMÁGENES DE PRODUCTOS
-- ============================================================
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  url text not null,
  sort_order integer not null default 0,
  created_at timestamptz default now()
);

-- FK imágenes → productos (seguro)
alter table public.product_images
  drop constraint if exists product_images_product_id_fkey;

alter table public.product_images
  add constraint product_images_product_id_fkey
  foreign key (product_id)
  references public.products(id)
  on delete cascade;

-- Índices imágenes
create index if not exists idx_product_images_product
  on public.product_images(product_id);

create index if not exists idx_product_images_sort
  on public.product_images(product_id, sort_order);

-- ============================================================
-- 4. CONFIGURACIÓN TIENDA
-- ============================================================
create table if not exists public.store_settings (
  id bigint primary key default 1,
  store_name text not null default 'Mi Tienda',
  store_description text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  whatsapp text not null default '',
  address text not null default '',
  logo_url text not null default ''
);

-- Asegurar solo 1 fila
alter table public.store_settings
  drop constraint if exists store_settings_single_row;

alter table public.store_settings
  add constraint store_settings_single_row check (id = 1);

insert into public.store_settings (id, store_name)
values (1, 'Mary Leggings')
on conflict (id) do nothing;

-- ============================================================
-- 5. RLS TABLAS (deshabilitado para catálogo público)
-- ============================================================
alter table public.categories disable row level security;
alter table public.products disable row level security;
alter table public.product_images disable row level security;
alter table public.store_settings disable row level security;

-- ============================================================
-- 6. STORAGE BUCKET
-- ============================================================
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Políticas storage
drop policy if exists "product-images-select" on storage.objects;
create policy "product-images-select"
  on storage.objects for select
  using (bucket_id = 'product-images');

drop policy if exists "product-images-insert" on storage.objects;
create policy "product-images-insert"
  on storage.objects for insert
  with check (bucket_id = 'product-images' and auth.role() = 'authenticated');

drop policy if exists "product-images-delete" on storage.objects;
create policy "product-images-delete"
  on storage.objects for delete
  using (bucket_id = 'product-images' and auth.role() = 'authenticated');

-- ============================================================
-- 7. SEED DATA
-- ============================================================
insert into public.categories (nombre) values
  ('Deportivas'),
  ('Casual'),
  ('Compresión'),
  ('Yoga'),
  ('Largo completo')
on conflict (nombre) do nothing;

insert into public.products (codigo, nombre, color, categoria_id, imagen_url) values
  ('ML-001', 'Leggins Deportivos Ajustados', 'Negro', 1, ''),
  ('ML-002', 'Leggins Casual Cómodos', 'Gris', 2, ''),
  ('ML-003', 'Leggins de Compresión Alta', 'Azul Marino', 3, ''),
  ('ML-004', 'Leggins para Yoga Suaves', 'Rosa', 4, ''),
  ('ML-005', 'Leggins Largo Completo Clásicos', 'Negro', 5, ''),
  ('ML-006', 'Leggins Deportivos con Bolsillos', 'Verde Oliva', 1, ''),
  ('ML-007', 'Leggins Casual Acanalados', 'Beige', 2, '')
on conflict (codigo) do nothing;

-- ============================================================
-- 8. MIGRAR imágenes existentes (products.imagen_url → product_images)
-- ============================================================
insert into public.product_images (product_id, url, sort_order)
select
  p.id,
  p.imagen_url,
  0
from public.products p
where p.imagen_url is not null
  and p.imagen_url != ''
  and not exists (
    select 1
    from public.product_images pi
    where pi.product_id = p.id
      and pi.url = p.imagen_url
  );



solucion, -- ============================================================
-- 8. SEED DATA (SIN DEPENDER DE IDs)
-- ============================================================

-- Categorías
INSERT INTO public.categories (nombre)
VALUES
('Deportivas'),
('Casual'),
('Compresión'),
('Yoga'),
('Largo completo')
ON CONFLICT (nombre) DO NOTHING;

-- Productos

INSERT INTO public.products (codigo, nombre, color, categoria_id, imagen_url)
SELECT
    'ML-001',
    'Leggins Deportivos Ajustados',
    'Negro',
    c.id,
    ''
FROM public.categories c
WHERE c.nombre = 'Deportivas'
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.products (codigo, nombre, color, categoria_id, imagen_url)
SELECT
    'ML-002',
    'Leggins Casual Cómodos',
    'Gris',
    c.id,
    ''
FROM public.categories c
WHERE c.nombre = 'Casual'
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.products (codigo, nombre, color, categoria_id, imagen_url)
SELECT
    'ML-003',
    'Leggins de Compresión Alta',
    'Azul Marino',
    c.id,
    ''
FROM public.categories c
WHERE c.nombre = 'Compresión'
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.products (codigo, nombre, color, categoria_id, imagen_url)
SELECT
    'ML-004',
    'Leggins para Yoga Suaves',
    'Rosa',
    c.id,
    ''
FROM public.categories c
WHERE c.nombre = 'Yoga'
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.products (codigo, nombre, color, categoria_id, imagen_url)
SELECT
    'ML-005',
    'Leggins Largo Completo Clásicos',
    'Negro',
    c.id,
    ''
FROM public.categories c
WHERE c.nombre = 'Largo completo'
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.products (codigo, nombre, color, categoria_id, imagen_url)
SELECT
    'ML-006',
    'Leggins Deportivos con Bolsillos',
    'Verde Oliva',
    c.id,
    ''
FROM public.categories c
WHERE c.nombre = 'Deportivas'
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.products (codigo, nombre, color, categoria_id, imagen_url)
SELECT
    'ML-007',
    'Leggins Casual Acanalados',
    'Beige',
    c.id,
    ''
FROM public.categories c
WHERE c.nombre = 'Casual'
ON CONFLICT (codigo) DO NOTHING;