-- ============================================================
-- Schema para Catálogo Mary Leggings
-- Modelo final basado en variantes
-- ============================================================

-- 1. TABLA CATEGORÍAS
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

-- 2. TABLA TIPOS DE PRODUCTO
CREATE TABLE IF NOT EXISTS public.product_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

-- 3. TABLA COLORES (normalizados)
CREATE TABLE IF NOT EXISTS public.colors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  codigo_hex text NOT NULL DEFAULT '#808080',
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- 4. TABLA PRODUCTOS
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text NOT NULL UNIQUE,
  slug text UNIQUE,
  nombre text NOT NULL,
  descripcion text NOT NULL DEFAULT '',
  categoria_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  tipo_id bigint REFERENCES public.product_types(id) ON DELETE SET NULL,
  disponible boolean NOT NULL DEFAULT true,
  destacado boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz
);

-- 5. TABLA VARIANTES DE PRODUCTOS (colores)
CREATE TABLE IF NOT EXISTS public.product_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  color_id bigint NOT NULL REFERENCES public.colors(id) ON DELETE RESTRICT,
  disponible boolean NOT NULL DEFAULT true,
  orden integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_variants_product ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_color ON public.product_variants(color_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_orden ON public.product_variants(orden);

-- 6. TABLA IMÁGENES DE VARIANTES
CREATE TABLE IF NOT EXISTS public.product_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id bigint NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_images_variant ON public.product_images(variant_id);

-- 7. ÍNDICES
CREATE INDEX IF NOT EXISTS idx_products_codigo ON public.products(codigo);
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);
CREATE INDEX IF NOT EXISTS idx_products_nombre ON public.products(nombre);
CREATE INDEX IF NOT EXISTS idx_products_categoria ON public.products(categoria_id);
CREATE INDEX IF NOT EXISTS idx_products_tipo ON public.products(tipo_id);
CREATE INDEX IF NOT EXISTS idx_products_destacado ON public.products(destacado);

-- 8. POLÍTICAS RLS
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.colors DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_types DISABLE ROW LEVEL SECURITY;

-- 9. TABLA CONFIGURACIÓN DE LA TIENDA
CREATE TABLE IF NOT EXISTS public.store_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_name text NOT NULL DEFAULT 'Mi Tienda',
  store_description text NOT NULL DEFAULT '',
  contact_email text NOT NULL DEFAULT '',
  contact_phone text NOT NULL DEFAULT '',
  address text NOT NULL DEFAULT '',
  logo_url text NOT NULL DEFAULT '',
  whatsapp text NOT NULL DEFAULT ''
);

INSERT INTO public.store_settings (id, store_name) VALUES (1, 'Mary Leggings')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.store_settings DISABLE ROW LEVEL SECURITY;

-- ============================================================
-- SEED DATA
-- ============================================================
INSERT INTO public.categories (nombre) VALUES
  ('Deportivas'), ('Casual'), ('Compresión'), ('Yoga'), ('Largo completo')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.product_types (nombre) VALUES
  ('Leggings'), ('Top'), ('Short'), ('Conjunto'), ('Accesorio')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.colors (nombre, codigo_hex) VALUES
  ('Negro', '#000000'), ('Blanco', '#FFFFFF'), ('Azul', '#0000FF'),
  ('Azul Marino', '#001F3F'), ('Rojo', '#FF0000'), ('Rosa', '#FF69B4'),
  ('Verde', '#008000'), ('Verde Oliva', '#808000'), ('Gris', '#808080'),
  ('Beige', '#F5F5DC'), ('Morado', '#800080'), ('Naranja', '#FFA500'),
  ('Amarillo', '#FFFF00'), ('Celeste', '#00BFFF'), ('Burdeos', '#800020')
ON CONFLICT (nombre) DO NOTHING;
