-- ============================================================
-- Schema para Catálogo Mary Leggings
-- Ejecutar en el SQL Editor de Supabase
-- ============================================================

-- 1. TABLA CATEGORÍAS
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz default now()
);

-- 2. TABLA PRODUCTOS
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  color text not null default '',
  categoria_id bigint references public.categories(id) on delete set null,
  imagen_url text not null default '',
  disponible boolean not null default true,
  fecha_activacion timestamptz default now(),
  created_at timestamptz default now()
);

-- 3. TABLA IMÁGENES DE PRODUCTOS
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  sort_order integer not null default 0,
  created_at timestamptz default now()
);

create index if not exists idx_product_images_product on public.product_images(product_id);

-- 4. ÍNDICES
create index if not exists idx_products_codigo on public.products(codigo);
create index if not exists idx_products_nombre on public.products(nombre);
create index if not exists idx_products_categoria on public.products(categoria_id);

-- 5. POLÍTICAS RLS (Row Level Security)
-- Deshabilitamos RLS para simplificar (solo admin tiene acceso a la tabla)
-- Si quieres habilitar RLS, configura las políticas apropiadas.
alter table public.categories disable row level security;
alter table public.products disable row level security;
alter table public.product_images disable row level security;

-- 6. BUCKET DE STORAGE para imágenes
-- Ver migration: supabase/migrations/00001_storage_bucket.sql
-- Ejecutar ese archivo en el SQL Editor de Supabase

-- 7. TABLA CONFIGURACIÓN DE LA TIENDA
create table if not exists public.store_settings (
  id bigint generated by default as identity primary key,
  store_name text not null default 'Mi Tienda',
  store_description text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  address text not null default '',
  logo_url text not null default ''
);

-- Insertar fila por defecto
insert into public.store_settings (id, store_name) values (1, 'Mary Leggings')
on conflict (id) do nothing;

alter table public.store_settings disable row level security;

-- ============================================================
-- SEED DATA - Ejecutar opcionalmente
-- ============================================================
insert into public.categories (nombre) values
  ('Deportivas'),
  ('Casual'),
  ('Compresión'),
  ('Yoga'),
  ('Largo completo')
on conflict (nombre) do nothing;

insert into public.products (codigo, nombre, color, categoria_id, imagen_url) values
  ('ML-001', 'Leggins Deportivos Ajustados', 'Negro', 1, ''),
  ('ML-002', 'Leggins Casual Cómodos', 'Gris', 2, ''),
  ('ML-003', 'Leggins de Compresión Alta', 'Azul Marino', 3, ''),
  ('ML-004', 'Leggins para Yoga Suaves', 'Rosa', 4, ''),
  ('ML-005', 'Leggins Largo Completo Clásicos', 'Negro', 5, ''),
  ('ML-006', 'Leggins Deportivos con Bolsillos', 'Verde Oliva', 1, ''),
  ('ML-007', 'Leggins Casual Acanalados', 'Beige', 2, '')
on conflict (codigo) do nothing;
