-- ============================================================
-- Schema para Catálogo Mary Leggings
-- ============================================================

-- 1. TABLA CATEGORÍAS
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz default now()
);

-- 2. TABLA TIPOS DE PRODUCTO
create table if not exists public.product_types (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz default now()
);

-- 3. TABLA COLORES (normalizados)
create table if not exists public.colors (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  codigo_hex text not null default '#808080',
  activo boolean not null default true,
  created_at timestamptz default now()
);

-- 4. TABLA PRODUCTOS
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  descripcion text not null default '',
  categoria_id bigint references public.categories(id) on delete set null,
  tipo_id bigint references public.product_types(id) on delete set null,
  disponible boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz
);

-- 5. TABLA VARIANTES DE PRODUCTOS (colores)
create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  color_id bigint not null references public.colors(id) on delete restrict,
  activo boolean not null default true,
  created_at timestamptz default now()
);

create index if not exists idx_product_variants_product on public.product_variants(product_id);
create index if not exists idx_product_variants_color on public.product_variants(color_id);

-- 6. TABLA IMÁGENES DE VARIANTES
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  variant_id bigint not null references public.product_variants(id) on delete cascade,
  url text not null,
  sort_order integer not null default 0,
  created_at timestamptz default now()
);

create index if not exists idx_product_images_variant on public.product_images(variant_id);

-- 7. ÍNDICES
create index if not exists idx_products_codigo on public.products(codigo);
create index if not exists idx_products_nombre on public.products(nombre);
create index if not exists idx_products_categoria on public.products(categoria_id);
create index if not exists idx_products_tipo on public.products(tipo_id);

-- 8. POLÍTICAS RLS
alter table public.categories disable row level security;
alter table public.colors disable row level security;
alter table public.products disable row level security;
alter table public.product_variants disable row level security;
alter table public.product_images disable row level security;
alter table public.product_types disable row level security;

-- 9. TABLA CONFIGURACIÓN DE LA TIENDA
create table if not exists public.store_settings (
  id bigint generated by default as identity primary key,
  store_name text not null default 'Mi Tienda',
  store_description text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  address text not null default '',
  logo_url text not null default '',
  whatsapp text not null default ''
);

insert into public.store_settings (id, store_name) values (1, 'Mary Leggings')
on conflict (id) do nothing;

alter table public.store_settings disable row level security;

-- ============================================================
-- SEED DATA
-- ============================================================
insert into public.categories (nombre) values
  ('Deportivas'), ('Casual'), ('Compresión'), ('Yoga'), ('Largo completo')
on conflict (nombre) do nothing;

insert into public.product_types (nombre) values
  ('Leggings'), ('Top'), ('Short'), ('Conjunto'), ('Accesorio')
on conflict (nombre) do nothing;

insert into public.colors (nombre, codigo_hex) values
  ('Negro', '#000000'), ('Blanco', '#FFFFFF'), ('Azul', '#0000FF'),
  ('Azul Marino', '#001F3F'), ('Rojo', '#FF0000'), ('Rosa', '#FF69B4'),
  ('Verde', '#008000'), ('Verde Oliva', '#808000'), ('Gris', '#808080'),
  ('Beige', '#F5F5DC'), ('Morado', '#800080'), ('Naranja', '#FFA500'),
  ('Amarillo', '#FFFF00'), ('Celeste', '#00BFFF'), ('Burdeos', '#800020')
on conflict (nombre) do nothing;
