-- ============================================================
-- Crear / reparar tabla product_images con FK a products
-- Ejecutar en el SQL Editor de Supabase
-- ============================================================

-- Crear tabla si no existe
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  url text not null,
  sort_order integer not null default 0,
  created_at timestamptz default now()
);

-- Agregar FK si no existe (seguro para re-ejecución)
do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints tc
    join information_schema.constraint_column_usage ccu
      on tc.constraint_name = ccu.constraint_name
    where tc.constraint_type = 'FOREIGN KEY'
      and tc.table_name = 'product_images'
      and ccu.column_name = 'product_id'
      and ccu.table_name = 'products'
  ) then
    alter table public.product_images
      add constraint product_images_product_id_fkey
      foreign key (product_id) references public.products(id)
      on delete cascade;
  end if;
end $$;

-- Índice
create index if not exists idx_product_images_product
  on public.product_images(product_id);
