-- ============================================================
-- Migration 00008: Refactor to variant-based product model
-- with normalized colors table
-- ============================================================

-- 1. Create product_types table
CREATE TABLE IF NOT EXISTS public.product_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.product_types DISABLE ROW LEVEL SECURITY;

-- 2. Create colors table (normalized)
CREATE TABLE IF NOT EXISTS public.colors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  codigo_hex text NOT NULL DEFAULT '#808080',
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.colors DISABLE ROW LEVEL SECURITY;

-- 3. Seed default colors
INSERT INTO public.colors (nombre, codigo_hex) VALUES
  ('Negro', '#000000'),
  ('Blanco', '#FFFFFF'),
  ('Azul', '#0000FF'),
  ('Azul Marino', '#001F3F'),
  ('Rojo', '#FF0000'),
  ('Rosa', '#FF69B4'),
  ('Verde', '#008000'),
  ('Verde Oliva', '#808000'),
  ('Gris', '#808080'),
  ('Beige', '#F5F5DC'),
  ('Morado', '#800080'),
  ('Naranja', '#FFA500'),
  ('Amarillo', '#FFFF00'),
  ('Celeste', '#00BFFF'),
  ('Burdeos', '#800020')
ON CONFLICT (nombre) DO NOTHING;

-- 4. Create product_variants with color_id FK
CREATE TABLE IF NOT EXISTS public.product_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  color_id bigint NOT NULL REFERENCES public.colors(id) ON DELETE RESTRICT,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_product_variants_product ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_color ON public.product_variants(color_id);
ALTER TABLE public.product_variants DISABLE ROW LEVEL SECURITY;

-- 5. Add tipo_id to products (if not exists)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS tipo_id bigint REFERENCES public.product_types(id) ON DELETE SET NULL;

-- 6. Rename disponible column (handle both cases)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'activo') THEN
    ALTER TABLE public.products RENAME COLUMN activo TO disponible;
  END IF;
END $$;

-- If neither activo nor disponible exists, add disponible
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'disponible') THEN
    ALTER TABLE public.products ADD COLUMN disponible boolean NOT NULL DEFAULT true;
  END IF;
END $$;

-- 7. Migrate existing data: group products by nombre, create variants
DO $$
DECLARE
  rec RECORD;
  new_product_id bigint;
  old_prod RECORD;
  color_rec RECORD;
  new_variant_id bigint;
BEGIN
  FOR rec IN
    SELECT DISTINCT nombre, categoria_id, descripcion, codigo
    FROM public.products
    WHERE color IS NOT NULL AND color != ''
    ORDER BY nombre
  LOOP
    IF EXISTS (
      SELECT 1 FROM public.product_variants pv
      JOIN public.products p ON p.id = pv.product_id
      WHERE p.nombre = rec.nombre
    ) THEN
      CONTINUE;
    END IF;

    INSERT INTO public.products (codigo, nombre, categoria_id, descripcion, disponible)
    VALUES (rec.codigo, rec.nombre, rec.categoria_id, rec.descripcion, true)
    RETURNING id INTO new_product_id;

    FOR old_prod IN
      SELECT DISTINCT ON (color) id, color
      FROM public.products
      WHERE nombre = rec.nombre AND color IS NOT NULL AND color != ''
      ORDER BY color, id
    LOOP
      -- Find or use existing color
      SELECT id INTO color_rec FROM public.colors WHERE nombre = old_prod.color;
      IF color_rec IS NULL THEN
        INSERT INTO public.colors (nombre, codigo_hex) VALUES (old_prod.color, '#808080')
        RETURNING id INTO color_rec;
      END IF;

      INSERT INTO public.product_variants (product_id, color_id, activo)
      VALUES (new_product_id, color_rec, true)
      RETURNING id INTO new_variant_id;

      -- Migrate images: update product_images to reference new variant
      -- product_images still has product_id at this point
      UPDATE public.product_images
      SET product_id = new_product_id
      WHERE product_id = old_prod.id;
    END LOOP;
  END LOOP;
END $$;

-- 8. Create new product_images table with variant_id
CREATE TABLE IF NOT EXISTS public.product_images_new (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id bigint NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_product_images_new_variant ON public.product_images_new(variant_id);

-- 9. Link images to variants based on color of original product
DO $$
DECLARE
  old_product RECORD;
  v_id bigint;
BEGIN
  FOR old_product IN
    SELECT p.id AS product_id, p.color, pi.id AS image_id, pi.url, pi.sort_order, pi.created_at
    FROM public.products p
    JOIN public.product_images pi ON pi.product_id = p.id
    WHERE p.color IS NOT NULL AND p.color != ''
  LOOP
    SELECT pv.id INTO v_id
    FROM public.product_variants pv
    JOIN public.colors c ON c.id = pv.color_id
    WHERE pv.product_id = old_product.product_id
      AND c.nombre = old_product.color
    LIMIT 1;

    IF v_id IS NOT NULL THEN
      INSERT INTO public.product_images_new (variant_id, url, sort_order, created_at)
      VALUES (v_id, old_product.url, old_product.sort_order, old_product.created_at);
    END IF;
  END LOOP;
END $$;

-- 10. Replace old product_images
DROP TABLE IF EXISTS public.product_images;
ALTER TABLE public.product_images_new RENAME TO product_images;
ALTER TABLE public.product_images DISABLE ROW LEVEL SECURITY;

-- 11. Remove old duplicated products
DELETE FROM public.products
WHERE id NOT IN (
  SELECT DISTINCT ON (nombre) id
  FROM public.products
  ORDER BY nombre, id
);

-- 12. Remove old columns from products
ALTER TABLE public.products DROP COLUMN IF EXISTS color;
ALTER TABLE public.products DROP COLUMN IF EXISTS imagen_url;

-- 13. Ensure codigo exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'codigo') THEN
    ALTER TABLE public.products ADD COLUMN codigo text;
  END IF;
END $$;

-- Make codigo unique if not already
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'products_codigo_key'
  ) THEN
    -- Update any null codigo values first
    UPDATE public.products SET codigo = 'ML-' || id WHERE codigo IS NULL OR codigo = '';
    ALTER TABLE public.products ADD CONSTRAINT products_codigo_key UNIQUE (codigo);
  END IF;
END $$;

-- 14. Add indices
CREATE INDEX IF NOT EXISTS idx_products_nombre ON public.products(nombre);
CREATE INDEX IF NOT EXISTS idx_products_codigo ON public.products(codigo);
CREATE INDEX IF NOT EXISTS idx_products_categoria ON public.products(categoria_id);
CREATE INDEX IF NOT EXISTS idx_products_tipo ON public.products(tipo_id);

-- 15. Disable RLS on all tables
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.colors DISABLE ROW LEVEL SECURITY;

-- 16. Insert default product types
INSERT INTO public.product_types (nombre) VALUES
  ('Leggings'),
  ('Top'),
  ('Short'),
  ('Conjunto'),
  ('Accesorio')
ON CONFLICT (nombre) DO NOTHING;

-- 17. Assign types to products by name pattern
UPDATE public.products SET tipo_id = (SELECT id FROM public.product_types WHERE nombre = 'Leggings' LIMIT 1)
WHERE tipo_id IS NULL AND (nombre ILIKE '%legg%' OR nombre ILIKE '%leg%');

UPDATE public.products SET tipo_id = (SELECT id FROM public.product_types WHERE nombre = 'Top' LIMIT 1)
WHERE tipo_id IS NULL AND nombre ILIKE '%top%';

UPDATE public.products SET tipo_id = (SELECT id FROM public.product_types WHERE nombre = 'Short' LIMIT 1)
WHERE tipo_id IS NULL AND nombre ILIKE '%short%';
