-- ============================================================
-- Migration 00009: Safe patch to add variant-based model
-- Preserves ALL existing data. No deletes, no duplicates.
-- ============================================================

-- ============================================================
-- PHASE 1: Create new tables (no data impact)
-- ============================================================

-- 1a. product_types
CREATE TABLE IF NOT EXISTS public.product_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.product_types DISABLE ROW LEVEL SECURITY;

-- 1b. colors
CREATE TABLE IF NOT EXISTS public.colors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  codigo_hex text NOT NULL DEFAULT '#808080',
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.colors DISABLE ROW LEVEL SECURITY;

-- 1c. product_variants
CREATE TABLE IF NOT EXISTS public.product_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  color_id bigint NOT NULL REFERENCES public.colors(id) ON DELETE RESTRICT,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_product_variants_product ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_color ON public.product_variants(color_id);
ALTER TABLE public.product_variants DISABLE ROW LEVEL SECURITY;

-- ============================================================
-- PHASE 2: Seed reference data
-- ============================================================

-- 2a. Default colors
INSERT INTO public.colors (nombre, codigo_hex) VALUES
  ('Negro', '#000000'),
  ('Blanco', '#FFFFFF'),
  ('Azul', '#0000FF'),
  ('Azul Marino', '#001F3F'),
  ('Rojo', '#FF0000'),
  ('Rosa', '#FF69B4'),
  ('Verde', '#008000'),
  ('Verde Oliva', '#808000'),
  ('Gris', '#808080'),
  ('Beige', '#F5F5DC'),
  ('Morado', '#800080'),
  ('Naranja', '#FFA500'),
  ('Amarillo', '#FFFF00'),
  ('Celeste', '#00BFFF'),
  ('Burdeos', '#800020'),
  ('Sin color', '#CCCCCC')
ON CONFLICT (nombre) DO NOTHING;

-- 2b. Default product types
INSERT INTO public.product_types (nombre) VALUES
  ('Leggings'),
  ('Top'),
  ('Short'),
  ('Conjunto'),
  ('Accesorio')
ON CONFLICT (nombre) DO NOTHING;

-- ============================================================
-- PHASE 3: Add missing columns to existing tables
-- ============================================================

-- 3a. products.codigo
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'products' AND column_name = 'codigo'
  ) THEN
    ALTER TABLE public.products ADD COLUMN codigo text;
  END IF;
END $$;

-- 3b. products.tipo_id
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'products' AND column_name = 'tipo_id'
  ) THEN
    ALTER TABLE public.products ADD COLUMN tipo_id bigint
      REFERENCES public.product_types(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 3c. Ensure products.disponible exists
--     (00007 already adds it, but guard against partial runs)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'products' AND column_name = 'disponible'
  ) THEN
    ALTER TABLE public.products ADD COLUMN disponible boolean NOT NULL DEFAULT true;
  END IF;
END $$;

-- 3d. product_images.variant_id (nullable initially)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'product_images' AND column_name = 'variant_id'
  ) THEN
    ALTER TABLE public.product_images ADD COLUMN variant_id bigint;
  END IF;
END $$;

-- ============================================================
-- PHASE 4: Create product_variants for every existing product
--           One variant per product, using its color text.
--           No new rows in products.
-- ============================================================

DO $$
DECLARE
  prod RECORD;
  color_id_val bigint;
  variant_id_val bigint;
  has_color_col boolean;
BEGIN
  -- Check if products.color column exists
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'products' AND column_name = 'color'
  ) INTO has_color_col;

  FOR prod IN
    SELECT p.id, p.color, p.disponible
    FROM public.products p
    WHERE NOT EXISTS (
      SELECT 1 FROM public.product_variants pv
      WHERE pv.product_id = p.id
    )
  LOOP
    -- Find or create the color row
    IF has_color_col AND prod.color IS NOT NULL AND TRIM(prod.color) != '' THEN
      SELECT id INTO color_id_val
      FROM public.colors
      WHERE nombre = TRIM(prod.color)
      LIMIT 1;

      IF color_id_val IS NULL THEN
        INSERT INTO public.colors (nombre, codigo_hex)
        VALUES (TRIM(prod.color), '#808080')
        ON CONFLICT (nombre) DO NOTHING;
        SELECT id INTO color_id_val
        FROM public.colors
        WHERE nombre = TRIM(prod.color)
        LIMIT 1;
      END IF;
    ELSE
      -- No color text: use "Sin color"
      SELECT id INTO color_id_val
      FROM public.colors
      WHERE nombre = 'Sin color'
      LIMIT 1;
    END IF;

    -- Create the variant
    INSERT INTO public.product_variants (product_id, color_id, activo)
    VALUES (prod.id, color_id_val, COALESCE(prod.disponible, true))
    RETURNING id INTO variant_id_val;

    -- Link this product's images to the new variant
    UPDATE public.product_images
    SET variant_id = variant_id_val
    WHERE product_id = prod.id
      AND (variant_id IS NULL OR variant_id != variant_id_val);
  END LOOP;
END $$;

-- ============================================================
-- PHASE 5: Make variant_id NOT NULL on product_images
--           Only after Phase 4 linked all images.
-- ============================================================

-- Verify no orphan images remain
DO $$
DECLARE
  orphans bigint;
BEGIN
  SELECT count(*) INTO orphans
  FROM public.product_images
  WHERE variant_id IS NULL;

  IF orphans > 0 THEN
    RAISE EXCEPTION 'Migration aborted: % product_images have no variant_id. Fix data before proceeding.', orphans;
  END IF;
END $$;

-- Safe to enforce NOT NULL now
ALTER TABLE public.product_images
  ALTER COLUMN variant_id SET NOT NULL;

-- ============================================================
-- PHASE 6: Add FK constraint from product_images → product_variants
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints tc
    JOIN information_schema.constraint_column_usage ccu
      ON tc.constraint_name = ccu.constraint_name
    WHERE tc.constraint_type = 'FOREIGN KEY'
      AND tc.table_name = 'product_images'
      AND ccu.column_name = 'variant_id'
      AND ccu.table_name = 'product_variants'
  ) THEN
    ALTER TABLE public.product_images
      ADD CONSTRAINT product_images_variant_id_fkey
      FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
      ON DELETE CASCADE;
  END IF;
END $$;

-- ============================================================
-- PHASE 7: Auto-assign product types by name pattern
-- ============================================================

UPDATE public.products
SET tipo_id = (SELECT id FROM public.product_types WHERE nombre = 'Leggings' LIMIT 1)
WHERE tipo_id IS NULL
  AND (nombre ILIKE '%legg%' OR nombre ILIKE '%leg%');

UPDATE public.products
SET tipo_id = (SELECT id FROM public.product_types WHERE nombre = 'Top' LIMIT 1)
WHERE tipo_id IS NULL
  AND nombre ILIKE '%top%';

UPDATE public.products
SET tipo_id = (SELECT id FROM public.product_types WHERE nombre = 'Short' LIMIT 1)
WHERE tipo_id IS NULL
  AND nombre ILIKE '%short%';

-- ============================================================
-- PHASE 8: Ensure codigo has values for all products
-- ============================================================

UPDATE public.products
SET codigo = 'ML-' || id
WHERE codigo IS NULL OR codigo = '';

-- ============================================================
-- PHASE 9: Add index for product_images.variant_id
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_product_images_variant
  ON public.product_images(variant_id);

-- ============================================================
-- PHASE 10: Add indices for new columns
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_products_codigo ON public.products(codigo);
CREATE INDEX IF NOT EXISTS idx_products_nombre ON public.products(nombre);
CREATE INDEX IF NOT EXISTS idx_products_categoria ON public.products(categoria_id);
CREATE INDEX IF NOT EXISTS idx_products_tipo ON public.products(tipo_id);

-- ============================================================
-- PHASE 11: Disable RLS on all tables
-- ============================================================

ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.colors DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_types DISABLE ROW LEVEL SECURITY;

-- ============================================================
-- PHASE 12: Validation
-- ============================================================

DO $$
DECLARE
  total_products bigint;
  total_variants bigint;
  total_images bigint;
  images_with_variant bigint;
  products_without_variant bigint;
BEGIN
  SELECT count(*) INTO total_products FROM public.products;
  SELECT count(*) INTO total_variants FROM public.product_variants;
  SELECT count(*) INTO total_images FROM public.product_images;
  SELECT count(*) INTO images_with_variant
    FROM public.product_images WHERE variant_id IS NOT NULL;
  SELECT count(*) INTO products_without_variant
    FROM public.products p
    WHERE NOT EXISTS (
      SELECT 1 FROM public.product_variants pv WHERE pv.product_id = p.id
    );

  RAISE NOTICE '=== Migration 00009 Validation ===';
  RAISE NOTICE 'Products: %', total_products;
  RAISE NOTICE 'Variants: %', total_variants;
  RAISE NOTICE 'Images: %', total_images;
  RAISE NOTICE 'Images with variant_id: %', images_with_variant;
  RAISE NOTICE 'Products without variant: %', products_without_variant;

  IF products_without_variant > 0 THEN
    RAISE WARNING '% products have no variant!', products_without_variant;
  END IF;

  IF images_with_variant != total_images THEN
    RAISE WARNING '% of % images missing variant_id!',
      total_images - images_with_variant, total_images;
  END IF;

  IF total_variants < total_products THEN
    RAISE WARNING 'More products (%) than variants (%) — expected equal.',
      total_products, total_variants;
  END IF;
END $$;
