-- ============================================================
-- Migration 00011: Add sizes (tallas) management
-- + ensure product_types table exists
-- ============================================================

-- 1. Ensure product_types exists (fix for Tipos menu)
CREATE TABLE IF NOT EXISTS public.product_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.product_types DISABLE ROW LEVEL SECURITY;

-- 2. Create sizes table
CREATE TABLE IF NOT EXISTS public.sizes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.sizes DISABLE ROW LEVEL SECURITY;

-- 3. Create product_sizes junction table
CREATE TABLE IF NOT EXISTS public.product_sizes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  size_id bigint NOT NULL REFERENCES public.sizes(id) ON DELETE CASCADE,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  UNIQUE(product_id, size_id)
);
ALTER TABLE public.product_sizes DISABLE ROW LEVEL SECURITY;

-- 4. Indexes
CREATE INDEX IF NOT EXISTS idx_product_sizes_product ON public.product_sizes(product_id);
CREATE INDEX IF NOT EXISTS idx_product_sizes_size ON public.product_sizes(size_id);

-- 5. Seed default sizes
INSERT INTO public.sizes (nombre) VALUES
  ('XS'), ('S'), ('M'), ('L'), ('XL'), ('XXL')
ON CONFLICT (nombre) DO NOTHING;
